### PR TITLE
Migrates to SDK style project files

### PR DESCRIPTION
**Pull request by ChrSteinert**
Initially, without much change, this migrates to the new project file format.

- [x] Migrate mail project
- [x] Migrate test project
- [x] Make build succeed
- [x] Make test run/successd

### CODE REVIEW

**Comment by ChrSteinert** [comment]
The problem seems to be, that AppVeyor uses on older MSBuild version. @forki can you help me out here?

**Comment by forki** [comment]
maybe https://github.com/SAFE-Stack/SAFE-BookStore/blob/master/appveyor.yml#L10 ??

**Comment by ChrSteinert** [comment]
Can you check what image is running there? Maybe we need the VS2017 image for MSBuild 15‽

**Comment by forki** [comment]
no idea

**Comment by ChrSteinert** [comment]
Can you easily change the image?

**Comment by forki** [comment]
no idea. I did not configure it.

**Comment by ChrSteinert** [comment]
https://ci.appveyor.com/project/SteffenForkmann/excelprovider/ …
I just assumed. Will look around myself 😉

**Comment by ChrSteinert** [comment]
Perfect - now only to test to go!

**Comment by ChrSteinert** [comment]
🎉

**Comment by forki** [comment]
hugs!

**Comment by quintusm** [comment]
Any chance of getting this pull request merged?

**Comment by dsyme** [comment]
Apologies for the delay.  Would someone like to come on as co-maintainer for this repo?  I'll help for now :)

**Comment by quintusm** [comment]
HI Don

I would not mind becoming a maintainer, not sure if I am competent though. Will definitely need assistance initially.  If somebody more experienced volunteers I would not be offended if you rather select them. 

I am an active user of this type provider in a production app, though, so I have some vested interest in it's being moved forward...

**Comment by dsyme** [comment]
Hi @quintusm, That's great!  I can add you as a co-maintainer.   I will try to help you.

What is your nuget.org handle?

**Comment by quintusm** [comment]
HI @dsyme.  I haven't been registered on nuget.org before as I have never needed to be. I have done so now though, my handle  there is also qmarais

**Comment by dsyme** [comment]
@quintusm OK, you are now registered

**Pull request merged**
