### PR TITLE
seems fixed sheetname issues like

### PR DESCRIPTION
**Pull request by ingted**
seems fixed sheetname issues like https://github.com/fsprojects/ExcelProvider/issues/77

### CODE REVIEW

**Comment by quintusm** [comment]
Looks promising. I will have a look and merge if it seems correct.

Thank you for contribution

**Comment by quintusm** [comment]
I would like to create a test to show the failure case before pulling this pull request. Then we can confirm and illustrate that it fixes the issue.  And make sure it doesn't get broken again in future.

**Comment by ingted** [comment]
If it's ok, I would like to help to create the tests (however I need several days to get to know about the testing stuff in this repo). How would you like it? @quintusm

**Comment by quintusm** [comment]
That will be very cool. I am happy to let you work on it and then you can ask me at any time if you get stuck with something or need assistance, and I will try to help you.

**Comment by ingted** [comment]
I suddenly bump into an issue that the only way; which I could figure out now; is to send the code into a fsi session on the fly... or the test project is not buildable... however it sounds really heavy to start a FsiEvaluationSession object -> evaluate the script having the ExcelProvider library loaded -> determine the test result by the diagnose messages return by the fsi session... 

Do you like the fsi way? @quintusm 
If yes, I think I know how to develop the test cases now.

image

image

**Comment by ingted** [comment]
PS. When I try to use paket to add Microsoft.NET.Test.Sdk into test project, it succeeded but the reference doesn't show up in Packages section of the project. So I need to add 
```
<ItemGroup>
  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
</ItemGroup>
```
into fsproj file to make "Run Tests" shown in right-click menu of the project...

**Comment by quintusm** [comment]
What IDE are you using? Visual Studio, VSCode or something else?

For now please be aware that if you run the build it also runs the tests. If all the tests pass the RunTests target will be successful.

You can also run the following command : dotnet fake run build.fsx --target RunTests

**Comment by quintusm** [comment]
What IDE are you using? Visual Studio, VSCode or something else?

For now please be aware that if you run the build it also runs the tests. If all the tests pass the RunTests target will be successfull.

You can also run the following command : dotnet fake run build.fsx --target RunTests

**Comment by quintusm** [comment]
Adding Microsoft.NET.Test.Sdk to the paket.references file in the ExcelProvider.Tests folder should have the same effect as adding the itemgroup reference in the project file

**Comment by ingted** [comment]
Created another PR.
https://github.com/fsprojects/ExcelProvider/pull/93

**Comment by ingted** [comment]
Changed to this PR. https://github.com/fsprojects/ExcelProvider/pull/94

**Pull request closed without merging**
